ANTHROPIC_API_KEY: 
GEMINI_API_KEY: 
GROQ_API_KEY: 
OPENAI_API_KEY: 
MISTRAL_API_KEY: 
SERPER_API_KEY: 
LLM_SHERPA_SERVER: http://localhost:5010/api/parseDocument?renderFormat=all&useNewIndentParser=yes
NEO4J_URI: 
NEO4J_USERNAME: 
NEO4J_PASSWORD: 